version: '3.9'

services:
  flask:
    build: .
    container_name: Flask-app
    ports:
      - "5000:5000"
    networks: 
      - flask-redis-net

  redis:
    image: redis:alpine
    container_name: Redis
    networks: 
      - flask-redis-net

networks:
  flask-redis-net:

